schema_version: 1

context:
  name: plateau
  version: 4.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/plateau-${{ version }}.tar.gz
  sha256: 75aac62514720a68abd0cc8a5581f93b04ecaccafd5e85f099a2fe6837bcb232

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools-scm
  run:
    - attrs
    - click
    - dask-core >=2022.5.1
    - decorator
    - msgpack-python >=0.5.2
    - minimalkv >=1.4.2
    - numpy !=1.15.0,!=1.16.0
    - pandas >=0.23.0,!=1.0.0
    - prompt-toolkit
    - pyarrow >=4
    - python >=${{ python_min }}
    - pyyaml
    - simplejson
    - toolz
    - urlquote >=1.1.3
    - zstandard

tests:
  - python:
      imports:
        - plateau
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE.txt
  summary: A consistent table management library in Python. Flat files, flat land.
  homepage: https://pypi.org/project/plateau/

extra:
  recipe-maintainers:
    - IzerOnadimQC
    - DamianB-BitFlipper
    - xhochy
    - janjagusch
